"""Copy of utils/image_util.py for standalone cloud_inference use."""

import csv


def load_boxes(file: str) -> list:
    """Load the bounding boxes from a csv file generated by MakeSense."""
    with open(file, "r") as f:
        reader = csv.reader(f)
        next(reader)
        return list(reader)


def labels_to_points(labels: list) -> list[list[int]]:
    points = []
    for label in labels:
        points.append(
            [
                int(label[1]),
                int(label[2]),
                int(label[1]) + int(label[3]),
                int(label[2]) + int(label[4]),
            ]
        )
    return points


def crop(img, cp):
    return img[cp[1] : cp[3], cp[0] : cp[2]]


class Cropper:
    def __init__(self, file: str):
        self.boxes = load_boxes(file)
        self.points = labels_to_points(self.boxes)

    def crop(self, img, idx):
        return crop(img, self.points[idx])
